version: '3'
services:
  mybuildenv:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mybuildenv
    restart: unless-stopped
    tty: true
    volumes:
      - /home/lll/tmp:/home/lll
    environment:
      http_proxy: http://10.0.2.15:1080
      https_proxy: http://10.0.2.15:1080

